apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-q1wf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-q1wf
    app.kubernetes.io/part-of: test-rhtap-54-app
  name: devfile-sample-code-with-quarkus-q1wf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-q1wf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-q1wf
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-54-tenant/test-rhtap-54-app/devfile-sample-code-with-quarkus-q1wf@sha256:ae34108ec240c58b5b871986df9314566c870e6d49d02a9c5349ebebcfe55f9f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
